name: Upload artifacts
on: [push]
on:
  workflow_dispatch   

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Upload artifact
      - run: echo "uploading artifacts" > upload.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: world.txt
          
      - name: Download Artifact
      - uses: actions/download-artifact
