name: Upload artifacts

on:
  workflow_dispatch   

jobs:
  build:
    runs-on: windows-latest
    steps:
    - run: pwd
     # - run: echo "uploading artifacts" > upload.txt
      
     # - name: Upload artifact1
     # - uses: actions/upload-artifact@v3
      #  with:
       #   name: my-artifact
        #  path: upload.txt
        
