name: Upload artifacts

on:
  workflow_dispatch   

jobs:
  build:
    runs-on: windows-latest
    steps:
    - run: pwd
    - run: echo "uploading artifacts" > D:/a/POCone/POCone/upload.txt
      
    - name: Upload artifact1
      uses: actions/upload-artifact@v3
      with:
         name: my-artifact
         path: D:/a/POCone/POCone/upload.txt
    
    - name: Download artifact
        
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
    
    - name: Display structure of downloaded files
      run: ls -R
      
    - name: Semantic Versoning
      id: versioning
      uses: paulhatch/semantic-version@v4.0.2
      with:
        branch: main
        tag_prefixes: "y"
        major_pattern: "Breaking_Change:"
        minor_pattern: "feat:"
        format: "v${major}.${minor}.${patch}-prereleases$(increment)"
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrests.github_token }}
      with:
        tag_name: ${{ steps.versioning.outputs.version }}
        release_name: ${{ steps.versioning.outputs.version }}
        prerelease: true
        
